cd $WORKSPACE/log4client
CWD=`pwd`
make env
export PATH=$CWD/ENV/bin:$PATH
make all
make runtests
sed 's/<!-- Generated by coverage.py: http:\/\/nedbatchelder.com\/code\/coverage\/3.4b1 -->/<sources><source>${SOURCES}<\/source><\/sources>/g' coverage.xml > covered.xml
make pylint > /dev/null 2>&1
make release

